wandb_version: 1

Domain:
  desc: null
  value: CWRU
_wandb:
  desc: null
  value:
    cli_version: 0.10.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
batch_size:
  desc: null
  value: 64
betas:
  desc: null
  value:
  - 0.9
  - 0.999
cuda_device:
  desc: null
  value: '0'
data_dir:
  desc: null
  value: ./datasets
dropout:
  desc: null
  value: 0.0
gamma:
  desc: null
  value: 0.2
imba:
  desc: null
  value: false
load_path:
  desc: null
  value: ''
lr:
  desc: null
  value: 0.01
lr_scheduler:
  desc: null
  value: stepLR
max_epoch:
  desc: null
  value: 30
model_name:
  desc: null
  value: CNN
momentum:
  desc: null
  value: 0.9
normlizetype:
  desc: null
  value: mean-std
num_workers:
  desc: null
  value: 4
opt:
  desc: null
  value: sgd
random_state:
  desc: null
  value: 2024
save:
  desc: null
  value: false
save_dir:
  desc: null
  value: ./ckpt
signal_size:
  desc: null
  value: 2048
source:
  desc: null
  value: CWRU_0
steps:
  desc: null
  value: '10'
target:
  desc: null
  value: CWRU_1
tradeoff:
  desc: null
  value:
  - exp
  - exp
  - exp
train_mode:
  desc: null
  value: single_source
weight_decay:
  desc: null
  value: 0.0005
